
'''
Trabalho prático em grupo 5 pessoas
Entrega Dia 01/07
Valor: 30 pontos

Entregar o print do codigo fonte e do sistema em execução

    SISTEMA DE VOTAÇÃO URNA ELETRONICA: 
    TEMOS UMA ELEIÇÃO CHEGANDO PARA PREFEITO DE GOTHAN CITY EN 2024: TEMOS
    4 CANDIDATOS: CORINGA, MULHER GATO, CHARADA, E HERA VENENOSA

    SÃO 20 ELEITORES HABILITADOS EM UMA DETERMINADA SEÇÃO.
    CRIE UM SISTEMA QUE RECEBA OS VOTOS DOS ELEITORES, CONTABILIZANDO OS VOTOS
    E DIZENDO QUEM GANHOU E O TOTAL DE VOTOS E RECEBIDOS POR CADA CANDIDATO'''